<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CareerLiveryManager.Core\CareerLiveryManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\Montserrat.ttf" />
    <Resource Include="Resources\Fonts\JetBrainsMono.ttf" />
    <Resource Include="Resources\Icon\clm.ico" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Icon\clm.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
